#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
cd $DIR/..

$DIR/install-ripgrep

ED=local/ebt-data
if [ -e $ED ]; then
  pushd $ED > /dev/null
  git pull
  popd > /dev/null
else
  echo "$SCRIPT: cloning $ED"
  mkdir -p local
  git clone https://github.com/ebt-site/ebt-data $ED
fi

npm install --save scv-bilara@latest
rm -rf api/Seeker*
rm -f local/examples.json
$DIR/js/examples.js
$DIR/js/authors.js

if [ "$1" == "PUSH" ]; then
  $DIR/git-commit-version PUSH; RC=$?
  if [ "$RC" == "42" ]; then
    echo "$SCRIPT: no changes to commit"
  elif [ "$RC" == "0" ]; then
    echo "$SCRIPT: updating npm"
    $DIR/publish-npm
  else
    echo "$SCRIPT: exiting with error code $RC"
    exit $RC;
  fi
fi
